```{r Load Library}
library(readxl)
library(reshape2)
library(data.table)
library(plyr)
library(dplyr)
library(rstanarm)
library("lmPerm")
library("coin")
library(bayesplot)
library(brms)
library("gtools")
library(rstan)
```

```{r load date}
Research_Data <- read_excel("../../Data/Research_Data_Anonymized.xlsx")

Research_Data = Research_Data %>% mutate(Full_Attendance = !is.na(D2_Color) & !is.na(D1_Color))

data_by_homework = melt(data = setDT(Research_Data), variable.name = "Homework N", id.vars = c("ID", "Section", "Age", "246_Required","Highschool_Stats", "D1_Method", "D2_Method", "M_Overall_Score", "F_Overall_Score","Num_Tried_D2","Pre_Homework_Score_Average","Pre_Homework_Average_Incorrect","Full_Attendance"),
measure = patterns("_status", "_corr", "_incorr"),
value.name = c("Status", "Correct", "Incorrect") )

Homework_Info <- read_excel("../../Data/Homework_Info.xlsx") #This spreadsheet contains the general info about each homework problem, including type of problem
for(each_student in 1:length(data_by_homework$ID)){
  
  data_by_homework$Type_E[each_student] = Homework_Info$E[as.numeric(data_by_homework$`Homework N`[each_student])]
  data_by_homework$Type_I[each_student] = Homework_Info$I[as.numeric(data_by_homework$`Homework N`[each_student])]
  data_by_homework$Type_C[each_student] = Homework_Info$C[as.numeric(data_by_homework$`Homework N`[each_student])]
  data_by_homework$Days_Since[each_student] = Homework_Info$Days[as.numeric(data_by_homework$`Homework N`[each_student])]
  data_by_homework$Pretest_Score[each_student] = (Research_Data$P_Overall_Score[Research_Data$ID == data_by_homework$ID[each_student]])
  data_by_homework$Pretest_Type_Score[each_student] = (Research_Data$P_Total_Type_Correct[Research_Data$ID == data_by_homework$ID[each_student]])
  data_by_homework$Pretest_Cond_Score[each_student] = (Research_Data$P_Total_Cond_Correct[Research_Data$ID == data_by_homework$ID[each_student]])

}

rm(Homework_Info, each_student)

post_study_data_by_homework = data_by_homework[data_by_homework$Days_Since != 0]
#post_study_data_by_homework$Status = floor(post_study_data_by_homework$Status)

pre_study_data_by_homework = data_by_homework[data_by_homework$Days_Since == 0]
#pre_study_data_by_homework$Status = floor(pre_study_data_by_homework$Status)

formated_homework_data = post_study_data_by_homework
#method in study
formated_homework_data[,"D1_Method_Videos"] <- 0
formated_homework_data[,"D1_Method_Worksheet"] <- 0
formated_homework_data[,"D1_Method_Neither"] <- 0
formated_homework_data[,"D2_Method_Videos"] <- 0
formated_homework_data[,"D2_Method_Worksheet"] <- 0
formated_homework_data[,"D2_Method_Neither"] <- 0


for(ii in 1:length(formated_homework_data$ID)){
  
  if(is.na(formated_homework_data$D1_Method[ii])){
    formated_homework_data$D1_Method_Neither[ii] = 1
  }

  else if(formated_homework_data$D1_Method[ii] == "Videos"){
    formated_homework_data$D1_Method_Videos[ii] = 1
  }
  else if(formated_homework_data$D1_Method[ii] == "Worksheet"){
    formated_homework_data$D1_Method_Worksheet[ii] = 1
  }
  if(is.na(formated_homework_data$D2_Method[ii])){0
    formated_homework_data$D2_Method_Neither[ii] = 1
  }
  else if(formated_homework_data$D2_Method[ii] == "Videos"){
    formated_homework_data$D2_Method_Videos[ii] = 1
  }
  else if(formated_homework_data$D2_Method[ii] == "Worksheet"){
    formated_homework_data$D2_Method_Worksheet[ii] = 1
  }

}


rm(ii)
#time since study
formated_homework_data$Time_Since = as.numeric(as.factor(post_study_data_by_homework$Days_Since))

#interaction between method and time


formated_homework_data$D1_Method_temp = as.numeric(as.factor(post_study_data_by_homework$D1_Method)) - 1
formated_homework_data$D2_Method_temp = as.numeric(as.factor(post_study_data_by_homework$D2_Method)) - 1

#honors
formated_homework_data$Honors = post_study_data_by_homework$Section == 501

#Age

formated_homework_data$Age = as.numeric(as.factor(post_study_data_by_homework$Age))

#246 Required
formated_homework_data$'246_Required' = as.numeric(as.factor(post_study_data_by_homework$'246_Required'))

formated_homework_data$'Num_Tried' = as.numeric(as.factor(post_study_data_by_homework$Num_Tried_D2))

formated_homework_data = na.omit(data.frame(
  ID = formated_homework_data$ID, 
  D1_Method_Videos = formated_homework_data$D1_Method_Videos, 
  D2_Method_Videos = formated_homework_data$D2_Method_Videos,  
  D1_Method_Worksheet = formated_homework_data$D1_Method_Worksheet, 
  D2_Method_Worksheet = formated_homework_data$D2_Method_Worksheet,  
  D1_Method_Neither = formated_homework_data$D1_Method_Neither, 
  D2_Method_Neither = formated_homework_data$D2_Method_Neither,  
  Required = formated_homework_data$'246_Required', 
  Status = formated_homework_data$Status, 
  Incorrect = formated_homework_data$Incorrect, 
  Correct = as.factor(formated_homework_data$Correct), 
  Type_E = formated_homework_data$Type_E, 
  Type_I = formated_homework_data$Type_I, 
  Type_C = formated_homework_data$Type_C, 
  Days_Since = formated_homework_data$Days_Since,
  Days_Since_Adj = (formated_homework_data$Days_Since - 6) / 37,
  Num_Tried = formated_homework_data$Num_Tried,
  Honors = formated_homework_data$Honors,
  Pretest_Score = formated_homework_data$Pretest_Score,
  Pretest_Type_Score = formated_homework_data$Pretest_Type_Score,
  Pretest_Cond_Score = formated_homework_data$Pretest_Cond_Score,
  Pre_Homework_Score_Average = formated_homework_data$Pre_Homework_Score_Average, 
  Pre_Homework_Average_Incorrect = formated_homework_data$Pre_Homework_Average_Incorrect,
  Full_Attendance = formated_homework_data$Full_Attendance
  )
  )
for(ii in 1:nrow(formated_homework_data)){
  if(formated_homework_data$Correct[ii] == 2){
    formated_homework_data$Correct[ii] = 1
  }
}
formated_homework_data = na.omit(formated_homework_data)
formated_homework_data 
data_by_exam = melt(data = setDT(Research_Data), variable.name = "Exam_Question", id.vars = c("First_Name", "ID", "Section","Highschool_Stats", "D1_Method", "D2_Method", "M_Overall_Score", "F_Overall_Score","Num_Tried_D2","Pre_Homework_Score_Average","Post_Homework_Score_Average","P_Overall_Score","Full_Attendance"),
measure = patterns("EE"),
value.name = c("Question_Correct")
)

data_by_exam[,"Exam_Number"] <- 0
for(each_question in 1:length(data_by_exam$ID)){
  if(substr(data_by_exam$Exam_Question[each_question],1,3) == "EE3"){
    data_by_exam$Exam_Number[each_question] = 0;
  }
  else{
    data_by_exam$Exam_Number[each_question] = 1;
  }
}
data_by_exam
```

```{r Exam Question Correct Model}

Question_Correct_model = stan_glm(Question_Correct ~ Exam_Number + Post_Homework_Score_Average + D1_Method  + Num_Tried_D2 +M_Overall_Score +F_Overall_Score,
                    data = data.frame(data_by_exam),
                    prior = normal(),
                    prior_intercept = normal(),
                    family=binomial(link = "logit")
                    )
summary(Question_Correct_model)
mcmc_intervals(Question_Correct_model, pars=c("D1_MethodWorksheet","Exam_Number","Post_Homework_Score_Average","M_Overall_Score","F_Overall_Score", "Num_Tried_D2"), prob = .80, prob_outer = .95)  + ggtitle("Exam Model") + scale_y_discrete(labels = c(
      "D1_MethodWorksheet" = "Worksheet on Day One",
      "Exam_Number" = "Exam Number",
      "M_Overall_Score" = "Mid-Study Quiz",
      "F_Overall_Score" = "End of Study Quiz",
      "Num_Tried_D2"="Number of Practice Problems Attempted Day 2 of Study",
      "Post_Homework_Score_Average" = "Average Homework Score Post Study"
      )
    )
percent_above_zero(Question_Correct_model, 4)
```

```{r Inccorect Count Model}
incor_model = stan_glm(Incorrect ~ Num_Tried + D1_Method_Worksheet + Days_Since_Adj + D1_Method_Worksheet + Honors + Pre_Homework_Average_Incorrect + Pretest_Score + Type_E + Type_I + Type_C,
                    data = data.frame(formated_homework_data),
                    prior = normal(),
                    prior_intercept = normal()
                    )
mcmc_intervals(incor_model, pars=c("D1_Method_Worksheet","Pre_Homework_Average_Incorrect","Pretest_Score","Num_Tried","HonorsTRUE","Days_Since_Adj"), prob = .80, prob_outer = .95)+ ggtitle("Model 2") + scale_y_discrete(labels = c(
      "Num_Tried" = "# of Attempted Practice Problems",
      "D1_Method_Worksheet" = "Worksheet on Day One",
      "HonorsTRUE" = "Honors",
      "Day2" = "Day 2",
      "Full_AttendanceTRUE" = "Full Attendance",
      "Pretest_Score" = "Pretest Score",
      "Days_Since_Adj"="Days Since Study",
      "Pre_Homework_Average_Incorrect" = "Student's Average # of Incorrect Prior to Study"
      )
    )

```

```{r Correct Homework Answer Model}
corr_model = stan_glm(Correct ~ Num_Tried + Days_Since_Adj + D1_Method_Worksheet + Honors + Pretest_Score + Type_E + Type_I + Type_C + Full_Attendance,
                    data = data.frame(formated_homework_data),
                    prior = normal(),
                    prior_intercept = normal(),
                    family=binomial(link = "logit")
                    )
mcmc_intervals(corr_model, pars=c("D1_Method_Worksheet","Pretest_Score","Num_Tried","HonorsTRUE","Days_Since_Adj","Full_AttendanceTRUE"), prob = .80, prob_outer = .95) + ggtitle("Model 1") + scale_y_discrete(labels = c(
      "Num_Tried" = "# of Attempted Practice Problems",
      "D1_Method_Worksheet" = "Worksheet on Day One",
      "HonorsTRUE" = "Honors",
      "Day2" = "Day 2",
      "Full_AttendanceTRUE" = "Full Attendance",
      "Pretest_Score" = "Pretest Score",
      "Days_Since_Adj"="Days Since Study"
      )
    )

```


```